spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5434/ssubench
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.jwt.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server.port=8080

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=${SHUTDOWN_TIMEOUT:30s}

server.tomcat.connection-timeout=${HTTP_REQUEST_TIMEOUT:30s}
server.tomcat.keep-alive-timeout=${HTTP_KEEP_ALIVE_TIMEOUT:65s}

jwt.expiration=${JWT_EXPIRES_IN:24h}